<?php
require_once APP . '/schema.php';
require_once APP . '/seed/seed.php';

/**
 * Shared installer used by /install/ (web) and app/cli/install.php (CLI).
 */
final class Installer
{
    public static function requirements(): array
    {
        return [
            'PHP 8.0 or newer' => version_compare(PHP_VERSION, '8.0.0', '>='),
            'PDO extension' => extension_loaded('pdo'),
            'PDO MySQL or SQLite driver' => extension_loaded('pdo_mysql') || extension_loaded('pdo_sqlite'),
            'DOM / XML extension' => class_exists('DOMDocument'),
            'GD image library (image optimisation)' => extension_loaded('gd'),
            'mbstring extension' => extension_loaded('mbstring'),
            '/app folder is writable (config file)' => is_writable(APP),
            '/app/storage folder is writable' => is_dir(STORAGE) ? is_writable(STORAGE) : is_writable(APP),
            '/uploads folder is writable' => is_dir(ROOT . '/uploads') ? is_writable(ROOT . '/uploads') : is_writable(ROOT),
        ];
    }

    /**
     * @param array $db    ['driver'=>'mysql'|'sqlite','host','port','name','user','pass','sqlite_path']
     * @param array $admin ['name','username','email','password']
     */
    public static function run(array $db, array $admin, array $opts = []): void
    {
        if (!is_dir(STORAGE)) {
            @mkdir(STORAGE, 0755, true);
        }
        if (!is_dir(ROOT . '/uploads')) {
            @mkdir(ROOT . '/uploads', 0755, true);
        }
        if (($db['driver'] ?? 'mysql') === 'sqlite' && empty($db['sqlite_path'])) {
            $db['sqlite_path'] = 'app/storage/database.sqlite';
        }
        DB::connect($db);
        if (DB::tableExists('users') && (int)DB::val('SELECT COUNT(*) FROM users') > 0 && empty($opts['force'])) {
            throw new RuntimeException('This database already contains an installation. Use an empty database.');
        }
        schema_install();
        DB::tx(function () use ($admin, $opts) {
            seed_database();
            DB::insert('users', [
                'username' => trim($admin['username']),
                'email' => strtolower(trim($admin['email'])),
                'name' => trim($admin['name'] ?: $admin['username']),
                'password' => password_hash($admin['password'], PASSWORD_DEFAULT),
                'role' => 'admin',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            Settings::set('notify_email', strtolower(trim($admin['email'])));
            Settings::set('seo_noindex', !empty($opts['noindex']) ? '1' : '0');
            Settings::set('installed_at', now());
        });

        $config = [
            'installed' => true,
            'debug' => false,
            'app_key' => bin2hex(random_bytes(32)),
            'site_url' => rtrim((string)($opts['site_url'] ?? ''), '/'),
            'base_path' => defined('BASE_PATH') ? BASE_PATH : '',
            'db' => $db,
        ];
        self::writeConfig($config);
    }

    public static function writeConfig(array $config): void
    {
        $php = "<?php\n// Generated by the website installer on " . date('c') . ".\n// Keep this file private. It is excluded from Git and blocked from web access.\nreturn " . var_export($config, true) . ";\n";
        if (file_put_contents(APP . '/config.php', $php, LOCK_EX) === false) {
            throw new RuntimeException('Could not write app/config.php. Make the /app folder writable and try again.');
        }
        @chmod(APP . '/config.php', 0640);
    }
}
